version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: warcoat-vault
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warcoat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - warcoat_network

  rabbitmq:
    image: rabbitmq:latest-management
    container_name: warcoat-relay
    environment:
      RABBITMQ_DEFAULT_USER: warcoat
      RABBITMQ_DEFAULT_PASS: warcoat
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - warcoat_network

networks:
  warcoat_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: